name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Build Electron app
      run: npm run electron:build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}
        path: |
          dist_electron/*.exe
          dist_electron/*.dmg
          dist_electron/*.AppImage
          dist_electron/*.deb
          dist_electron/*.rpm
        if-no-files-found: ignore
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          artifacts/dist-ubuntu-latest/*
          artifacts/dist-windows-latest/*
          artifacts/dist-macos-latest/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
