name: Security Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/services/security/**'
      - 'src/types/security.ts'
  # Manual trigger
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Install TypeDoc
        run: npm install --no-save typedoc
        
      - name: Generate documentation
        run: npx typedoc --out docs/security src/services/security src/types/security.ts
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/security
          publish_branch: gh-pages
          destination_dir: security
          keep_files: true
